CREATE DATABASE APNABI;
USE APNABI;

CREATE TABLE USUARIO (
	NOMBRE VARCHAR(50) PRIMARY KEY,
    CONTRASEÑA VARCHAR(50) NOT NULL
);

INSERT INTO USUARIO VALUES
("w","1");

CREATE TABLE EMPRESA (
    COD_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOM_EMPRESA VARCHAR(100) NOT NULL,
    SECTOR ENUM("Agricultura_Ganaderia", "BienesConsumo", "ComercioElectronico", "Comercio_Establecimientos", "Construccion", "Deporte_Ocio",
	"Energia_MedioAmbiente", "Finanzas_Seguros_BienesInmuebles", "Internet", "Logistica_Transporte", "MediosComunicacion_Marketing",
    "Metalurgia_Electronica", "ProductosQuimicos_MateriasPrimas", "Salud_IndustriaFarmaceutica", "Servicios", "Sociedad", "Tecnologia_Telecomunicaciones",
    "Turismo_Hosteleria", "Vida"),
    PUESTO VARCHAR(100),
    DATOSCONTACTO VARCHAR(200),
    CONTACTOEMPRESA VARCHAR(100),
    CONTACTOAPNABI VARCHAR(30) NOT NULL,
    ESTADO ENUM("Informado", "Valorando_Interesado", "PlanificandoInserciones", "ProximoAño", "NoInteresado")
);

INSERT INTO EMPRESA (NOM_EMPRESA, SECTOR, PUESTO, DATOSCONTACTO, CONTACTOEMPRESA, CONTACTOAPNABI, ESTADO) VALUES
("Deportes Urbanos de Exterior S.L", "Deporte_Ocio", "Almacen", "info@deportesurbanos.com", null, "Selene", "Informado"),
("Sualdi", "Metalurgia_Electronica", "Mozo/a Almacen", "sualdi@sualdi.com", null, "Selene", "Informado"),
("TSB", "Internet", "Mozo/a Almacen", "marc.pascual008@tsbtrans.com", "Marc Pascual", "Selene", "Informado"),
("Between Technology", "Internet", null, "LinkedIn", "Noemi Cotoré", "Selene", "Informado"),
("Versia", "Internet", null, "LinkedIn", "Garazi Mosteiro", "Selene", "Informado"),
("SEIDOR", "Internet", null, "LinkedIn", "Aida Morales Sedano", "Selene", "Informado"),
("Hotel Hesperia", "BienesConsumo", "Recepcion/Botones", "rheras@hesperia.com", "Raul Heras", "Alba", "Valorando_Interesado"),
("Ormazabal", "ProductosQuimicos_MateriasPrimas", "Almacen","mgi@ormazabal.com", "Miren Gutierrez", "Alba", "Valorando_Interesado"),
("Goaxen", "Deporte_Ocio", "Puesto multitarea (recepcion, monitor)", "info@goaxen.com", "Adrian Lopez", "Alba", "Valorando_Interesado"),
("Grupo Cofares", "Logistica_Transporte", "Almacen","vcuesta@cofares.es", "Virginia", "Alba", "Valorando_Interesado"),
("Cie Automotive", "Servicios", null, "jalvarez@cieautomotive.com", "Javier Alvarez", "Alba", "Informado"),
("Hotel Oriol", "BienesConsumo", null, "jeferecepcion.urhoriol@urh-hoteliers.com", "Jesus Garcia", "Gorka", "ProximoAño"),
("Druni Artea", "Comercio_Establecimientos", "Dependiente", "raquel.peiro@druni.es", "Raquel Peiro", "Gorka", "Informado"),
("Destination Consultant", "Turismo_Hosteleria", "Auxiliar administrativo", "gorka@basquecountry-spain-dmc.com", "Gorka Marques", "Alba", "Valorando_Interesado"),
("Estudios Durero", "Sociedad", null, "durero@estudiosdurero.com", "Ander Soriano Melgar", "Selene", "Informado"),
("Ibermatica", "Internet", null, "jarroyo@ayesa.com", "Jone Arroyo Aguado", "Selene", "ProximoAño"),
("Aplimedia", "Internet", null, "laura@aplimedia.com", "Laura Ferrer", "Selene", "NoInteresado"),
("I3", "Internet", null, null, null, "Selene", "NoInteresado"),
("GURENET", "Internet", null, "info@gurenet.com", "Iker Revuelta", "Selene", "Informado"),
("ZabalIT", "Internet", null, "administracion@zabalit.com", "Yolanda Chaves", "Selene", "Informado"),
("Serinfor", "Internet", null, "yulia@serinfor.net", null, "Selene", "Informado"),
("Abaco Creacion", "Internet", null, null, null, "Selene", "NoInteresado"),
("Linube", "Internet", null, "info@linube.com", null, "Selene", "Informado"),
("byvapps", "Internet", null, "astorga@byvapps.com", "Iban Astorga", "Selene", "Informado"),
("Ingeteam", "Metalurgia_Electronica", null, "People.Bizkaia@ingeteam.com", null, "Selene", "Informado"),
("Grupo Oesia", "Metalurgia_Electronica", null, "LinkedIn", "Monica Cuñado", "Selene", "Informado"),
("Grupo Oesia", "Metalurgia_Electronica", null, "scagigal@oesia.com", "Silvia Cagigal", "Selene", "Informado"),
("Grupo Oesia", "Metalurgia_Electronica", null, "mlconcepcion@oesia.com", "Marisa Concepcion", "Selene", "Informado"),
("Supermercado sqrups", "Comercio_Establecimientos", null, "bilbao@sqrups.es", "Mikel", "Alba", "Informado"),
("Sercotel Arenal Bilbao", "Turismo_Hosteleria", null, "direccion@sercotelarenalbilbao.com/629346347", "Beatriz Rodriguez", "Gorka", "Informado"),
("Herbolario Navarro", "Comercio_Establecimientos", null, "bidebarrieta@herbolarionavarro.es", "Marta", "Alba", "Informado"),
("Bestseller", "Servicios", "Recepcionista", "lucia.whitby@bestseller.com", "Lucia", "Alba", "ProximoAño"),
("Carrefour Atxuri", "Comercio_Establecimientos", "Gerente", "jose_robles_novas@carrefour.com", "Jose Robles", "Alba", "Informado"),
("Inycom", "Internet", "Directora de personas y talento", "marta.abad@inycom.es", "Marta", "Gorka", "Informado"),
("Veritas", "Comercio_Establecimientos", "Jefe area norte", "649984564", "Gontzal", "Alba", "Informado"),
("TEDI", "Comercio_Establecimientos", null, "722295620", "Fernanda", "Alba", "Informado"),
("Altafit Deusto", "Deporte_Ocio", "Gerente", "676053136", "Julio Valdes", "Alba", null),
("Burdinola", "Metalurgia_Electronica", "Human Resources Technician", "688881779/auskola@burdinola.com", "Alasne Uskola", "Selene", null),
("Cemosa", "Metalurgia_Electronica", "Delegado", "609402913/javier.salas@cemosaeuskocontrol.eus", "Javier Salas", "Selene", null),
("Innovalia", "Internet", "Project Manager", "674249706/cpolcaro@innovalia.org", "Carmen Polcaro", "Selene", null),
("Destination Consultant", "Turismo_Hosteleria", "General Manager", "685702815/gorka@basquecountry-spain-dmc.com", "Gorka Marques", "Alba", "Valorando_Interesado"),
("Pikara Magazine", "Servicios", "Recepcionista", "amigas@pikaramagazine.com", null, "Alba", "Valorando_Interesado"),
("Audiogrup", "Comercio_Establecimientos", "Senior HR Area Manager", "rrhh@audiogrup.es", "Miren Cenarruzabeitia", "Gorka", "Informado"),
("Gobesa", "Logistica_Transporte", "Responsable de RRHH", "esther@gobesa.com", "Esther Garizurieta", "Gorka", "Informado"),
("Saitec", "ProductosQuimicos_MateriasPrimas", "Técnica de Recursos Humanos", "671020056", "Lucia Manjon", "Alba", "Informado"),
("Hotel Gran Bilbao", "Turismo_Hosteleria", "Talent Manager", "talentmanager@hotelgranbilbao.com", "Maria Bernedo", "Alba", "Valorando_Interesado"),
("SAG Seguridad S.L.U.", "Logistica_Transporte", null, "administracion@sagseguridad.com", "Jesús", "Alba", "Informado"),
("Hotel Carlton", "Turismo_Hosteleria", "Director", "609345705", "Koldo Diaz", "Alba", null),
("H2site", "ProductosQuimicos_MateriasPrimas", "HR Talent Acquisition", "603 320 130/María.piedra@h2site.eu", "Maria Piedra", "Gorka", "Informado"),
("Grupo Eulen", null, "HR Talent Acquisition", "Linkedin", "Nerea Perujo", "Gorka", null),
("Grupo Uvesco", "Comercio_Establecimientos", "RRHH", "Linkedin", "Jone Cano Rodriguez", "Gorka", "NoInteresado"),
("Kategora Real Estare", null, "Director de RRHH", "jon.intxausti@kategora.com", "Jon Intxausti", "Gorka", "Informado"),
("Serveo", null, "RRHH", "maite.elorriagahernandez@serveo.com/659692670", "Maite Elorriaga", "Gorka", "Informado"),
("Lidl", "Comercio_Establecimientos", "Regional Head of people", "Linkedin", "Susana Garcia", "Gorka", "Valorando_Interesado"),
("Autobuses la union", "Logistica_Transporte", "Responsable RRHH", "adonate@autobuseslaunion.com", "Arantza Donate", "Gorka", "NoInteresado"),
("EIA21", "ProductosQuimicos_MateriasPrimas", "RRHH", "Linkedin", "Urko Martin Cobos", "Gorka", "Informado"),
("Parfois", "Comercio_Establecimientos", "Almacenero/a", null, null, "Alba", "Informado"),
("Hotel Melia", "BienesConsumo", "Cocina, sala o mantenimiento", null, null, "Alba", "Informado"),
("Viewnext", "Tecnologia_Telecomunicaciones", "Tecnico Sistemas", null, null, "Alba", "Valorando_Interesado"),
("Aclima", "ProductosQuimicos_MateriasPrimas", null, "empleoverde@aclima.eus", "Maider Fernandez", "Gorka", null),
("Lookiero", "Logistica_Transporte", "Mozo de almacen", "a.zarate@lookiero.com", "Amaia Zarate", "Gorka", "Valorando_Interesado"),
("Jardin Secreto", "Servicios", "Limpieza", "jardinsecretobilbao@gmail.com", "Tania", "Gorka", "Valorando_Interesado"),
("Growfulness Crecimiento Pleno", "Servicios", "Recepcion/administracion", "secretaria.centroatencionplena@gmail.com", "Javier Montero Gonzalez",
"Gorka", "Valorando_Interesado"),
("Versia", "Internet", "Tecnico Instalaciones informáticas", "garazi.mosteiro@versia.com/ebbibonmp@outlook.com/talento@versia.com", "Garazi y Iker Larrinaga",
"Selene", "Valorando_Interesado"),
("Tendam", "Comercio_Establecimientos", "Vendedor/a", "lorena.colmeiro@tendam.es", "Lorena Colmeiro", "Ellen", "Valorando_Interesado"),
("STEF", "Logistica_Transporte", "RRHH", "Noelia.Lorenzo@stef.com", "Noelia Lorenzo", "Gorka", "Valorando_Interesado"),
("Copistería KALKO", "Sociedad", null, null, null, "Gorka", null),
("Climbat", "Deporte_Ocio", "Coordinador", "coordinacionbarakaldo@climbat.com", "Alejandro Salazar", "Gorka", "Valorando_Interesado"),
("Coviran", "Comercio_Establecimientos", null, null, null, "Gorka", null),
("BILBOMÁTICA", "Internet", "Desarrollador Web", "sapolinar@bilbomatica.es", "Sofía Apolinar (RRHH)", "Rocío", "Valorando_Interesado"),
("TALIO", "Internet", "Administrador de Redes", "emalaina@talio.it", "Ernesto Malaina (RRHH)", "Rocío", "Informado"),
("Piugaz", "Servicios", "Mantenimiento", "unai@piugaz.com", "Unai (Encargado)", "Rocío", "Valorando_Interesado"),
("JYSK", "Comercio_Establecimientos", "Vendedor/a", "gul@jysk.com", "Gillermo", "Rocío", "Informado"),
("MITIE", "Servicios", "Limpiador/a o Lavandería", "patricia.zabaleta@mitie.com", "Patricia", "Rocío", "Informado"),
("HOFF", "Comercio_Establecimientos", "Vendedor/a", "659341677", "Janire Moreno", "Rocío", "Valorando_Interesado"),
("ALDI", "Comercio_Establecimientos", "Vendedor/a", "947427990", "Kathia", "Rocío", "Valorando_Interesado"),
("ARAVI", "Logistica_Transporte", "Almacén", "944276687 - patricia.losa@aravi.es", "Patricia", "Rocío", "Informado"),
("TEDI", "Comercio_Establecimientos", "Vendedor/a", "617303484", "Susana Serrano (encargada)", "Rocío", "Valorando_Interesado"),
("DINOSA", "Logistica_Transporte", "Almacén", "944565014 - comercial@dinosa.es", "Iñaki Bernaola (gerente)", "Rocío", "Informado"),
("GM Cash", "Comercio_Establecimientos", "Comercio y almacén", "maria.garrido@transgourmet.es", "María Garrido (RRHH)", "Rocío", "Informado"),
("Geek Planet", "Comercio_Establecimientos", "Vendedor/a", "bilbao@geekplanet.info", null, "Rocío", "Informado"),
("Mediamarkt", "Comercio_Establecimientos", "Vendedor/a", "laurperez@mediamarkt.es", "Laura Perez", "Rocío", "Informado"),
("Cocoon Bioscience", "Salud_IndustriaFarmaceutica", "Personal Almacén", "info@cocoonbio.com", "Sara", "Rocío", "Informado"),
("Acideka", "BienesConsumo", "Operador portuario", "mromo@acideka.com", "Miren Romo", "Alba", "Valorando_Interesado"),
("DEITEL", "MediosComunicacion_Marketing", "Informador Aeropuerto", "deitel@deiteldirect.es", "Nekane", "Alba", "NoInteresado");

CREATE TABLE CONTACTO (
    COD_CONTACTO INT PRIMARY KEY AUTO_INCREMENT,
    CONTACTO1 DATE,
    CONTACTO2 DATE,
    CONTACTO3 DATE,
    CONTACTO4 DATE,
    OBSERVACIONES VARCHAR(750),
    RESULTADOULTIMO ENUM("Comunicacion_SinRespuesta", "Respuesta_Pospuesta", "Reunion_Programada", "Respuesta_NoConcluyente", "Inicio_ValoracionOferta"),
    INFOULTIMO VARCHAR(500),
    RESULTADOFINAL ENUM("Oferta_Empleo", "Convenio_Colaboracion", "Medidas_Alternativas", "Relacion_Concluida", "Relacion_Pospuesta"),
    FECHARESOLUCION DATE,
    COD_EMPRESA INT,
    FOREIGN KEY (COD_EMPRESA)
        REFERENCES EMPRESA (COD_EMPRESA)
);

INSERT INTO CONTACTO (CONTACTO1, CONTACTO2, CONTACTO3, CONTACTO4, OBSERVACIONES, RESULTADOULTIMO, INFOULTIMO, RESULTADOFINAL, FECHARESOLUCION, COD_EMPRESA) VALUES
("2024-10-23", null, null, null, null, "Comunicacion_SinRespuesta", "Reunión el 08/05/2025", null, null, 1),
("2024-10-23", null, null, null, null, null, null, null, null, 2),
("2024-10-23", null, null, null, null, null, null, null, null, 3),
("2024-10-23", "2024-10-12", null, null, "2º contacto propuesta prácticas", "Inicio_ValoracionOferta",
"Pendiente de que nos den fecha para entrevistar a las dos personas que hemos enviado el CV", "Oferta_Empleo", "2023-10-4", 4),
("2024-10-23", "2024-10-23", null, null, "2º contacto propuesta prácticas", null, "Va a pasar la información a RRHH", null, "2023-10-5", 5),
("2024-9-20", "2024-10-9", null, null, "Propuesta de prácticas", "Reunion_Programada", "5 de mayo firma de convenio en oficinas de apnabi.","Convenio_Colaboracion",
"2023-10-6", 6),
("2024-9-20", "2024-10-9", null, null, null, null, null, null, "2023-10-7", 7),
("2024-10-21", null, null, null, null, "Inicio_ValoracionOferta",
"Kathia propone sacar ofertas ideadas para nosotros, antes que empezar a participar en procesos de selección que ya están en marcha. Va a realizar la propuesta a sus superiores",
"Relacion_Concluida", "2023-10-8", 8),
("2024-9-23", "2024-11-25", null, null, null, null, null, null, "2023-10-9", 9),
("2024-9-16", "2024-9-24", "2024-10-18", null, null, "Respuesta_Pospuesta",
"Tras reunión y presentación se les envía correo y responden que están valorando próximo contacto en mayo.", null, "2023-10-11", 10),
("2024-10-21", null, null, null, null, null, null, null, "2023-10-11", 11),
("2024-10-21", "2025-04-15", null, null, null, null, null, null, null, 12),
("2024-9-4", "2024-10-21", null, null, null, null, null, null, null, 13),
("2024-10-24", null, null, null, null, null, null, null, null, 14),
("2023-10-26", "2024-10-24", null, null, "2º contacto propuesta prácticas", null, null, null, null, 15),
("2024-10-23", null, null, null, "Propuesta Practicas / CEE", null, null, null, null, 16),
("2024-10-24", null, null, null, "Actualmente no es posible acoger prácticas", null, null, null, null, 17),
(null, null, null, null, null, null, null, null, null, 18),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 19),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 20),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 21),
("2024-10-24", null, null, null, null, null, null, null, null, 21),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 23),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 24),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 25),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 26),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 27),
("2024-10-24", null, null, null, "Propuesta de prácticas", null, null, null, null, 28),
("2024-10-24", "2024-11-6", null, null, null, null, null, null, null, 29),
("2024-10-24", null, null, null, null, null, null, null, null, 30),
("2024-10-24", null, null, null, null, null, null, null, null, 31),
("2024-10-30", "2024-11-6", null, null, null, null, null, null, null, 32),
("2024-11-6",  null, null, null, null, null, null, null, null, 33),
("2024-10-29", "2024-12-3", null, null, null, null, null, null, null, 34),
("2024-10-30", "2024-11-18", null, null, null, null, null, null, null, 35),
("2024-10-31", null, null, null, null, null, null, null, null, 36),
(null, null, null, null, null, null, null, null, null, 37),
(null, null, null, null, null, null, null, null, null, 38),
(null, null, null, null, null, null, null, null, null, 39),
(null, null, null, null, null, null, null, null, null, 40),
("2024-11-18", null, null, null, null, null, null, null, null, 41),
(null, null, null, null, "Ya han cubierto la vacante. Si en un futuro ven posibilidad nos avisarán", null, null, null, null, 42),
("2024-12-5", "2024-12-19", null, null, null, null, null, null, null, 43),
("2024-12-5", null, null, null, null, null, null, null, null, 44),
("2024-12-5", null, null, null, null, null, null, null, null, 45),
("2024-12-9", null, null, null, null, null, null, null, null, 46),
("2024-12-13", null, null, null, "Ya han cubierto la vacante", null, null, null, null, 47),
(null, null, null, null, null, null, null, null, null, 48),
("2025-1-14", null, null, null, "Nos contactarán en la segunda semana de febrero", null, null, null, null, 49),
(null, null, null, null, null, null, null, null, null, 50),
(null, null, null, null, null, null, null, null, null, 51),
(null, null, null, null, null, null, null, null, null, 52),
(null, null, null, null, null, null, null, null, null, 53),
("2025-2-4", null, null, null, "Contactaran en un par de semanas", null, null, null, null, 54),
(null, null, null, null, null, null, null, null, null, 55),
(null, null, null, null, null, null, null, null, null, 56),
("2025-1-20", null, null, null, null, null, null, null, null, 57),
("2025-1-20", null, null, null, null, null, null, null, null, 58),
("2025-1-20", null, null, null, "Enviamos perfiles, cuando haya un proceso de formacion nos avisaran", null, null, null, null, 59),
(null, null, null, null, null, null, null, null, null, 60), # PH for Contacto 1
("2025-1-21", null, null, null, "Contactaran en febrero. No buscan un puesto en concreto, mandaran la oferta para que les enviemos perfiles. Imprescindible coche.",
null, null, null, null, 61),
("2025-1-16", null, null, null, "Nos pasará la oferta de limpieza", null, null, null, null, 62),
("2025-1-24", null, null, null, "Que enviemos CV que cumplan en perfil", null, null, null, null, 63),
("2025-1-23", null, null, null, "Acompañamos a Ibon Moya en la entrevista y le contratan", null, null, null, null, 64),
("2025-1-24", null, null, null, null, null, null, null, null, 65),
("2025-1-27", null, null, null, null, null, null, null, null, 66),
(null, null, null, null, null, null, null, null, null, 67),
(null, null, null, null, null, null, null, null, null, 68),
(null, null, null, null, null, null, null, null, null, 69),
("2025-2-27", "2025-3-17", null, null,
"Mostraban interés inicialmente por contratar a personas con formación de Grado Superior de Desarrollo de Redes. Se ha tratado de contactar tras la reunión presencial, pero no ha vuelto a haber respuesta.",
null, null, null, null, 70),
("2025-3-4", null, null, null, "Próximamente saldrán vacantes y quieren contar con nosotros", null, null, null, null, 71),
("2025-3-10", "2025-3-17", null, null,
"Quieren a una persona para mantenimiento: Mantener zonas de almacenaje limpias, armar y desarmar presas de escalada, pintarlas... Se habla de 3 horas diarias, en horario de 9:00-12:00/10:00-13:00 por ejemplo",
null, null, null, null, 72),
("2025-3-17", null, null, null, null, null, null, null, null, 73),
("2025-3-10", "2025-3-28", null, null, null, null, null, null, null, 74),
("2025-3-24", "2025-3-25", null, null,
"Reunión 24/03 con la encargada, hay mucho interés por el servicio y se considera un puesto ideal para ser desempeñado por una de nuestras personas. Puesto de refuerzo a 16 horas semanales, con mucha orientación al apoyo a ventas y mantenimiento de la tienda, siempre con acompañamiento de otro profesional. Tienda pequeña, con almacén pequeño, en la que se lleva a cabo una venta muy personalizada y con un perfil de clientela muy “afable”. El 25 Janire me comenta que está pendiente del OK del Manager, que nos contactará",
null, null, null, null, 75),
("2025-3-24", "2025-3-27", null, null,
"Reunión de prospección por TEAMS el Jueves 27 a las 10:00. Tienen interés, de hecho, Kathia propone sacar ofertas ideadas para nosotros, antes que empezar a participar en procesos de selección que ya están en marcha. Va a realizar la propuesta a sus superiores",
null, null, null, null, 76),
("2025-3-21", null, null, null, null, null, null, null, null, 77),
("2025-3-31", null, null, null,
"Reunión presencial con la encargada. Presentará la propuesta al Jefe de Zona que vendrá a Bilbao el Jueves o Viernes. Ya le comento que sin problema puedo acercarme por la mañana, cualquiera de los dos días para presentarle a él el servicio.",
null, null, null, null, 78),
("2025-4-1", null, null, null,
"A pesar de tener la máquina de vending con nosotros, desconocían nuestra labor en lo tocante a inserción laboral de personas con autismo. Le gusta el servicio y la propuesta pero en estos momentos no tienen ninguna oferta o necesidad de contratación. Me solicita que le mande toda la información porque le interesa tenernos en cuenta para próximas oportunidades.",
null, null, null, null, 79),
("2025-4-1", null, null, null,
"Contacto con el encargado de tienda de Galdakao, Miguel, y me facilita el contacto de la responsable de RRHH a nivel nacional. Le envío la propuesta a su correo",
null, null, null, null, 80),
("2025-4-4", null, null, null,
"Jaime nos informa de que están buscando personal y de que quiere echar el CV. Lo que sucede realmente es que le han sugerido echar el CV, pero no hay ofertas activas. Nos pasan el contacto del jefe y nos comunicamos vía email de cara a la prospección.",
null, null, null, null, 81),
("2025-4-7", null, null, null, "Están bucando a gente en Zubiarte", null, null, null, null, 82),
("2025-4-7", null, null, null,
"Nos mencionan que el nivel de especialización de la empresa es muy grande, que contratan a personal con formación científica o en laboratorio. Le hablo de la posibilidad de participar en procesos concretos de laboratorio, de limpieza, de recepción, etc...",
null, null, null, null, 83),
("2025-4-22", null, null, null, null, null, null, null, null, 84),
("2025-4-24", null, null, null, "Para el puesto que ofrecían deciden no contratar a una persona con discapacidad", null, null, null, null, 85);

CREATE TABLE PERSONA (
    NOM_P VARCHAR(100) PRIMARY KEY,
    APOYO VARCHAR(50) NOT NULL,
    FORMACION ENUM("AT", "Primaria", "ESO", "EPA", "FP_Basica", "GM", "Bachillerato", "GS", "Universidad", "Master", "Doctorado") NOT NULL,
    ESPECIALIDAD VARCHAR(500) NOT NULL,
    SECTORINTERES ENUM("Agricultura_Ganaderia", "BienesConsumo", "ComercioElectronico", "Comercio_Establecimientos", "Construccion", "Deporte_Ocio",
	"Energia_MedioAmbiente", "Finanzas_Seguros_BienesInmuebles", "Internet", "Logistica_Transporte", "MediosComunicacion_Marketing",
    "Metalurgia_Electronica", "ProductosQuimicos_MateriasPrimas", "Salud_IndustriaFarmaceutica", "Servicios", "Sociedad", "Tecnologia_Telecomunicaciones",
    "Turismo_Hosteleria", "Vida") NOT NULL,
    CV VARCHAR(999),
    DISCAPACIDAD ENUM("Si", "No", "No_Sabe", "Tramitando") NOT NULL,
    ULTIMOAÑOTRABAJADO INT,
    INTERESESPERSONALES VARCHAR(500),
    SITUACIONACTUAL VARCHAR(500),
    EUSKERA ENUM("A1", "A2", "B1", "B2", "C1", "C2", "Conocimiento_NoAcreditado"),
    INGLES ENUM("A1", "A2", "B1", "B2", "C1", "C2", "Conocimiento_NoAcreditado"),
    OTROSIDIOMAS VARCHAR(50),
    LOCALIDAD ENUM("Abadiño", "Abanto_Zierbena", "Ajangiz", "Alonsotegi", "Amorebieta", "Amoroto", "Amurrio", "Arakaldo", "Arantzazu", "Areatza_Bilaro", "Arrankudiaga",
    "Arratzu", "Arrieta", "Arrigorriaga", "Artzentales", "Artziniega", "Aulesti", "AxpeAtxondo", "Ayala_Aiara", "Bakio", "Balmaseda", "Barakaldo", "Barrika", "Basauri",
    "Bedia", "Berango", "Bermeo", "Berriatua", "Berriz", "Bilbao", "Busturia", "CastroUrdiales", "Galdakao", "Galdames", "GamizFika", "Garai", "Gatika", "Gautegiz",
    "GazteluElexabeitia_Arteaga", "GernikaLumo", "Getxo", "Gizaburuaga", "Gordexola", "Gorliz", "Gueñes", "Ibarrangelu", "Igorre", "Ispaster", "Iurreta", "Izurtza",
    "KarrantzaHarana", "Kortezubi", "Lanestosa", "Larrabetzu", "Laudio_Llodio", "Laukiz", "Leioa", "Lekeitio", "Lemoa", "Lemoiz", "Lezama", "Loiu", "Lallabia", "Mañaria",
    "MarkinaXemein", "Maruri", "Mendata", "Mendexa", "Meñaka", "Morga", "Mundaka", "Mungia", "MunitibarArbatzegi_Gerrikaitz", "Murueta", "Muskiz", "Muxika", "Nabarniz",
    "Ondarroa", "Orduña", "Orozko", "Ortuella", "Otxandio", "Plentzia", "Portugalete", "Santurtzi", "Sestao", "Sondika", "Sopela", "Sopuerta", "Sukarrieta", "Trapagaran",
    "Turtzioz", "Ubide", "UgaoMiraballes", "Urduliz", "Urduña", "Usansolo", "Zaldibar", "Zalla", "Zamudio", "Zaratamo", "Zeanuri", "Zeberio", "Zierbena", "ZiortzaBolibar",
    "Zornotza") NOT NULL,
    ACCESIBILIDAD ENUM("Carnet_Coche", "Carnet", "Transporte_Publico") NOT NULL,
    OBSERVACIONES VARCHAR(500)
);

CREATE TABLE PERSONAINCLUSION(
	NOMBRE VARCHAR(50) PRIMARY KEY,
    APELLIDO VARCHAR(75) NOT NULL,
    EDAD INT NOT NULL,
    MUNICIPIO ENUM("Abadiño", "Abanto_Zierbena", "Ajangiz", "Alonsotegi", "Amorebieta", "Amoroto", "Amurrio", "Arakaldo", "Arantzazu", "Areatza_Bilaro", "Arrankudiaga",
    "Arratzu", "Arrieta", "Arrigorriaga", "Artzentales", "Artziniega", "Aulesti", "AxpeAtxondo", "Ayala_Aiara", "Bakio", "Balmaseda", "Barakaldo", "Barrika", "Basauri",
    "Bedia", "Berango", "Bermeo", "Berriatua", "Berriz", "Bilbao", "Busturia", "CastroUrdiales", "Galdakao", "Galdames", "GamizFika", "Garai", "Gatika", "Gautegiz",
    "GazteluElexabeitia_Arteaga", "GernikaLumo", "Getxo", "Gizaburuaga", "Gordexola", "Gorliz", "Gueñes", "Ibarrangelu", "Igorre", "Ispaster", "Iurreta", "Izurtza",
    "KarrantzaHarana", "Kortezubi", "Lanestosa", "Larrabetzu", "Laudio_Llodio", "Laukiz", "Leioa", "Lekeitio", "Lemoa", "Lemoiz", "Lezama", "Loiu", "Lallabia", "Mañaria",
    "MarkinaXemein", "Maruri", "Mendata", "Mendexa", "Meñaka", "Morga", "Mundaka", "Mungia", "MunitibarArbatzegi_Gerrikaitz", "Murueta", "Muskiz", "Muxika", "Nabarniz",
    "Ondarroa", "Orduña", "Orozko", "Ortuella", "Otxandio", "Plentzia", "Portugalete", "Santurtzi", "Sestao", "Sondika", "Sopela", "Sopuerta", "Sukarrieta", "Trapagaran",
    "Turtzioz", "Ubide", "UgaoMiraballes", "Urduliz", "Urduña", "Usansolo", "Zaldibar", "Zalla", "Zamudio", "Zaratamo", "Zeanuri", "Zeberio", "Zierbena", "ZiortzaBolibar",
    "Zornotza") NOT NULL,
    FORMACION ENUM("AT", "Primaria", "ESO", "EPA", "FP_Basica", "GM", "Bachillerato", "GS", "Universidad", "Master", "Doctorado") NOT NULL,
    ESPECIALIDAD VARCHAR(500) NOT NULL,
    OTROS VARCHAR(500),
    IDIOMA VARCHAR(50) NOT NULL,
    ULTIMOAÑOTRABAJADO INT,
    SECTORINTERES ENUM("Agricultura_Ganaderia", "BienesConsumo", "ComercioElectronico", "Comercio_Establecimientos", "Construccion", "Deporte_Ocio",
	"Energia_MedioAmbiente", "Finanzas_Seguros_BienesInmuebles", "Internet", "Logistica_Transporte", "MediosComunicacion_Marketing",
    "Metalurgia_Electronica", "ProductosQuimicos_MateriasPrimas", "Salud_IndustriaFarmaceutica", "Servicios", "Sociedad", "Tecnologia_Telecomunicaciones",
    "Turismo_Hosteleria", "Vida") NOT NULL,
	INTERESESPERSONALES VARCHAR(500),
    SITUACIONACTUAL VARCHAR(500),
	ACCESIBILIDAD ENUM("Carnet_Coche", "Carnet", "Transporte_Publico") NOT NULL,
	CV VARCHAR(999),
	PERSONAFACILITADORA VARCHAR(50) NOT NULL
);

CREATE TABLE PERSONAPRACTICAS (
	NOM VARCHAR(100) PRIMARY KEY,
    APOYO VARCHAR(50),
    FORMACION ENUM("AT", "Primaria", "ESO", "EPA", "FP_Basica", "GM", "Bachillerato", "GS", "Universidad", "Master", "Doctorado"),
    CURSO INT,
    CENTRO ENUM("CPIFP_JesuitakPoliteknikoa", "CPIFP_SalesianosDeusto", "CPIFP_Peñascal"," CIFP_Lea_Artibai",
	"CIFP_ArratiakoZulaibar_LanbideIkastegia", "CIFP_Uni_EibarErmua", "CIFP_ElorrietaErreka_Mari_GBLHI", "CPIFP_Harrobia",
	"CPIFP_MaristakDurango", "ZabalburuIkastetxea_S_Coop", "CIFP_ConstruccionBizkaia_LHII", "CPIFP_Barakaldo",
	"CIFP_Tartanga_GBLHI", "CIFP_Hosteleria_Hostalaritza_LHII", "CIFP_Andra_Mari_BHI", "CIFP_Fadura_GBLHI", "CIFP_Iurreta_GBLHI",
	"CIFP_EscuelaHosteleria_LHII", "CIFP_Repelega_GBLHI", "CIFP_SanJorge_GBLHI", "CIFP_Calasanz_LanbideIkastegia",
	"CPIFP_InnovacionSocialDiego_Berguices_Otxarkoaga", "CPIFP_SanViator", "UPV_EHU", "Universidad_Deusto",
	"EscuelaUniversitariaMagisterio_BAM_Begoñako_Andra_Mari", "UNED_UniversidadNacionalEspañola_A_Distancia", "CIFP_EmilioCampuzano",
	"CentroSanLuis", "CentroMikeldi", "TxorierriPoliteknikoa", "SopeñaBilbao", "CIFP_Bidebieta", "CIFP_Ibaiondo",
	"IES_DOLORESIBARRURI_BHI", "CIFP_ZORNOTZA_LHII", "CPES_ORUE_ESKOLA_BHIP", "IES_BARRUTIALDE_BHI", "IES_BALMASEDA_BHI",
    "CPES_BAGABILTZA_BHIP", "IMFPB_BITURITXA_BARAKALDO_OLHUI", "CPES_IKASAUTO_BHIP", "IMFPB_BASAURI_OLHUI",
    "CIFP_NAUTICOBERMEO_BERMEOKONAUTIKA_LHII", "IMFPB_BERMEO_OLHUI", "CIFP_TXURDINAGA_LHII", "IES_ESKURTZE_BHI",
    "IES_IBARREKOLANDA_BHI", "CPEIPS_ANGELESCUSTODIOS_HLBHIP", "CPES_ALMI_BHIP", "CPES_ARANGOYA_BHIP", "CPES_ARCE_BHIP",
    "CPES_ARMENGOL_BHIP", "CEINMARK", "CRUZROJA", "ESCUELASUPERIORHOSTELERIABILBAO", "FERNANDO_BHIP", "HERMANOSLARRINAGA_SL_BHIP",
    "MARIA_INMACULADA_BHIP", "STA_MARIA_DE_ARTAGAN_BHIP", "ADSIS_BILBAO_OLHIP", "PASTELERIA_COMERCIOBIZKAIA_OLHIP",
    "MARGOTU_OLHIP", "CPIFP_HARROBIA_LHIPI", "CIFP_AGRARIODERIO_DERIONEKAZARITZA_LHII", "IES_FRAYJUAN_DE_ZUMARRAGA_DURANGO_BHI",
    "IMFPB_DURANGO_OLHUI", "CPES_IBAIZABAL_IKASTOLA_BHIP", "IMFPB_ERANDIO_OLHUI", "CIFP_HOSTELERIA_OSTALARITZA_LHII",
    "IES_GERNIKA_BHI", "IMFPB_GERNIKA_LUMO_OLHUI", "CPFPB_ADSIS_GETXO_OLHIP", "IES_JOSEMIGUELBARANDIARAN_BHI",
	"CPFPB_ADSISLEIOA_OLHIP", "IES_LEKEITIO_BHI", "CPES_ESPERANZA_ALHAMA_BHIP", "IMFPB_ERMUA_MALLABIA_OLHUI",
    "CPFPB_PEÑASCALMARKINA_OLHIP", "IES_MUNGIA_BHI", "IMFPB_MUNGIA_OLHUI", "CPIFP_SOMORROSTRO_LHIPI", "IES_ONDARROA_BHI",
    "CPES_NTRA_SRA_DE_LA_ANTIGUA_BHIP", "CPFPB_MEATZALDEA_OLHIP", "IES_JUAN_ANTONIO_ZUNZUNEGUI_BHI", "IMFPB_PORTUGALETE_OLHUI",
    "CPES_XABIER_BHIP", "IMFPB_SANTURTZI_OLHUI, CPES_EIDE_BHIP", "IES_SATURNINO_DE_LA_PEÑA_BHI", "IMFPB_SESTAO_OLHUI",
    "CPEIPS_NTRA_SRA_DE_LA_ANTIGUA_HLBHIP", "CPEIPS_MARISTAS_SANMIGUEL_HLBHIP", "IES_MARTIN_DE_BERTENDONA_BHI"),
    FECHAS VARCHAR(50),
    DURACION VARCHAR(50),
    EMPRESAPRACTICAS VARCHAR(50),
    EMPRESANUESTRA BOOLEAN
);

CREATE TABLE ANALISISPUESTO(
	EMPRESA VARCHAR(100) PRIMARY KEY,
    PUESTO VARCHAR(50) NOT NULL,
    HORARIO VARCHAR(150) NOT NULL,
    FINDE ENUM("Si", "SoloSabados", "SoloDomingos", "No") NOT NULL,
    TURNOS BOOLEAN NOT NULL,
    MIN_FORMACION ENUM("AT", "Primaria", "ESO", "EPA", "FP_Basica", "GM", "Bachillerato", "GS", "Universidad", "Master", "Doctorado") NOT NULL,
    UBICACION VARCHAR(150) NOT NULL,
	SECTOR ENUM("Agricultura_Ganaderia", "BienesConsumo", "ComercioElectronico", "Comercio_Establecimientos", "Construccion", "Deporte_Ocio", "Energia_MedioAmbiente",
    "Finanzas_Seguros_BienesInmuebles", "Internet", "Logistica_Transporte", "MediosComunicacion_Marketing", "Metalurgia_Electronica", "ProductosQuimicos_MateriasPrimas",
    "Salud_IndustriaFarmaceutica", "Servicios", "Sociedad", "Tecnologia_Telecomunicaciones", "Turismo_Hosteleria", "Vida") NOT NULL,
    REQ_IDIOMAS VARCHAR(50) NOT NULL,
	CONTACTOEMPRESA VARCHAR(50) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    RESPONSABLEAPNABI VARCHAR(50) NOT NULL,
    ESFUERZOFISICO BOOLEAN NOT NULL,
    RESISTENCIA BOOLEAN NOT NULL,
    COMUNICACION ENUM("SinNecesidadComunicacion", "ComunicacionConPersonalEmpesa", "ComunicacionConPersonasExternasEmpresa",
    "ComunicacionConPersonalEmpresa_FueraEmpresa") NOT NULL,
    SENSORIALES ENUM("Ruido", "Luz", "Orden", "Limpieza") NOT NULL
);

DELIMITER //
CREATE PROCEDURE insertUser(NOMBRE VARCHAR(30), CONTRASEÑA VARCHAR(50))
BEGIN
	INSERT INTO USUARIO VALUES
	(NOMBRE,CONTRASEÑA);
END; //

DELIMITER //
CREATE PROCEDURE insertEmpresa(NOM_EMPRESA VARCHAR(100),
    SECTOR ENUM("Agricultura_Ganaderia", "BienesConsumo", "ComercioElectronico", "Comercio_Establecimientos", "Construccion", "Deporte_Ocio",
	"Energia_MedioAmbiente", "Finanzas_Seguros_BienesInmuebles", "Internet", "Logistica_Transporte", "MediosComunicacion_Marketing",
    "Metalurgia_Electronica", "ProductosQuimicos_MateriasPrimas", "Salud_IndustriaFarmaceutica", "Servicios", "Sociedad", "Tecnologia_Telecomunicaciones",
    "Turismo_Hosteleria", "Vida"),
    PUESTO VARCHAR(30), DATOSCONTACTO VARCHAR(50), CONTACTOEMPRESA VARCHAR(50), CONTACTOAPNABI VARCHAR(30),
    ESTADO ENUM("Informado", "Valorando_Interesado", "PlanificandoInserciones", "ProximoAño", "NoInteresado"))
BEGIN
	INSERT INTO EMPRESA (NOM_EMPRESA, SECTOR, PUESTO, DATOSCONTACTO, CONTACTOEMPRESA, CONTACTOAPNABI, ESTADO) VALUES
	(NOM_EMPRESA, SECTOR, PUESTO, DATOSCONTACTO, CONTACTOEMPRESA, CONTACTOAPNABI, ESTADO);
END; //

CREATE PROCEDURE insertContacto(NOM_EMP VARCHAR(100), CONTACTO1 DATE, CONTACTO2 DATE, CONTACTO3 DATE, CONTACTO4 DATE, OBSERVACIONES VARCHAR(500),
    RESULTADOULTIMO ENUM("Comunicacion_SinRespuesta", "Respuesta_Pospuesta", "Reunion_Programada", "Respuesta_NoConcluyente", "Inicio_ValoracionOferta"),
    INFOULTIMO VARCHAR(500),
    RESULTADOFINAL ENUM("Oferta_Empleo", "Convenio_Colaboracion", "Medidas_Alternativas", "Relacion_Concluida", "Relacion_Pospuesta"),
    FECHARESOLUCION DATE, COD_EMPRESA INT)
BEGIN
	DECLARE COD_EMP INT;
    SET COD_EMP:=(SELECT COD_EMPRESA FROM EMPRESA WHERE NOM_EMPRESA=NOM_EMP);
	
    INSERT INTO CONTACTO (CONTACTO1, CONTACTO2, CONTACTO3, CONTACTO4, OBSERVACIONES, RESULTADOULTIMO, INFOULTIMO, RESULTADOFINAL, FECHARESOLUCION, COD_EMPRESA) VALUES
	(CONTACTO1, CONTACTO2, CONTACTO3, CONTACTO4, OBSERVACIONES, RESULTADOULTIMO, INFOULTIMO, RESULTADOFINAL, FECHARESOLUCION, COD_EMP);
END; //
