package model;

public enum Sector {
	UNSET, ACTIVIDADES_DEPORTIVAS, ADMINISTRACION, ALMACEN_LOGISTICA, ARTES_GRAFICAS, COMERCIO, DOCENCIA, INDUSTRIAL, INFORMATICA,
	LIMPIEZA, RESTAURACION, SANIDAD, TURISMO, TRANSPORTE, IT, AUTOMOVILISTICO, MANTENIMIENTO, MARKETING
}
