package enums;

public enum Especialidad_TecnicoSuperior {
	Acondicionamiento Físico,
	Enseñanza y Animación Sociodeportiva,
	Administración y Finanzas,
	Asistencia a la Dirección,
	Ganadería y Asistencia en Sanidad Animal,
	Gestión Forestal y del Medio Natural,
	Paisajismo y Medio Rural
	Diseño y Edición de Publicaciones Impresas y Multimedia,
	Diseño y Gestión de la Producción Gráfica,
	Artista Fallero y Construcción de Escenografías,
	Comercio Internacional,
	Gestión de Ventas y Espacios Comerciales,
	Marketing y Publicidad,
	Transporte y Logística,
	Organización y Control de Obras de Construcción,
	Proyectos de Edificación,
	Proyectos de Obra Civil,
	Automatización y Robótica Industrial,
	Electromedicina Clínica,
	Mantenimiento Electrónico,
	Sistemas Electrotécnicos y Automatizados,
	Sistemas de Telecomunicaciones e Informáticos,
	Centrales Eléctricas,
	Eficiencia Energética y Energía Solar Térmica,
	Energías Renovables,
	Gestión del Agua,
	Construcciones Metálicas,
	Diseño en Fabricación Mecánica,
	Programación de la Producción en Fabricación Mecánica,
	Programación de la Producción en Moldeo de Metales y Polímeros,
	Agencias de Viajes y Gestión de Eventos,
	Dirección de Cocina,
	Dirección de Servicios de Restauración,
	Gestión de Alojamientos Turísticos,
	Guía, Información y Asistencias Turísticas,
	Asesoría de Imagen Personal y Corporativa,
	Caracterización y Maquillaje Profesional,
	Estilismo y Dirección de Peluquería,
	Estética Integral y Bienestar,
	Termalismo y Bienestar,
	Animaciones 3D, Juegos y Entornos Interactivos,
	Iluminación, Captación y Tratamiento de Imagen,
	Producción de Audiovisuales y Espectáculos,
	Realización de Proyectos Audiovisuales y Espectáculos,
	Sonido para Audiovisuales y Espectáculos,
	Procesos y Calidad en la Industria Alimentaria,
	Vitivinicultura,
	Administración de Sistemas Informáticos en Red,
	Desarrollo de Aplicaciones Multiplataforma,
	Desarrollo de Aplicaciones Web,
	Desarrollo de Proyectos de Instalaciones Térmicas y de Fluidos,
	Mantenimiento de Instalaciones Térmicas y de Fluidos,
	Mecatrónica Industrial,
	Diseño y Amueblamiento,
	Acuicultura,
	Organización del Mantenimiento de Maquinaria de Buques y Embarcaciones,
	Transporte Marítimo y Pesca de Altura,
	Fabricación de Productos Farmacéuticos, Biotecnológicos y Afines,
	Laboratorio de Análisis y de Control de Calidad,
	Química Industrial,
	Anatomía Patológica y Citodiagnóstico,
	Audiología Protésica,
	Documentación y Administración Sanitarias,
	Higiene Bucodental,
	Imagen para el Diagnóstico y Medicina Nuclear,
	Laboratorio Clínico y Biomédico,
	Ortoprótesis y Productos de Apoyo,
	Prótesis Dentales,
	Radioterapia y Dosimetría,
	Coordinación de Emergencias y Protección Civil,
	Educación y Control Ambiental,
	Química y Salud Ambiental,
	Animación Sociocultural y Turística,
	Educación Infantil,
	Formación para la Movilidad Segura y Sostenible,
	Integración Social,
	Mediación Comunicativa
	Promoción de Igualdad de Género,
	Diseño Técnico en Textil y Piel,
	Diseño y Producción de Calzado y Complementos,
	Patronaje y Moda,
	Vestuario a Medida y de Espectáculos,
	Automoción,
	Desarrollo y Fabricación de Productos Cerámicos,
	Mantenimiento de Sistemas Electrónicos y Aviónicos de Aeronaves,
	Tecnico en cuidados auxiliares de enfermeria
}
