package enums;

public enum Municipio {
	UNSET, ABADIÑO, ABANTO_ZIERBENA, AJANGIZ, ALONSOTEGI, AMOREBIETA, AMOROTO, AMURRIO, ARAKALDO, ARANTZAZU, AREATZA_BILARO,
	ARRANKUDIAGA, ARRATZU, ARRIETA, ARRIGORRIAGA, ARTZENTALES, ARTZINIEGA, AULESTI, AXPEATXONDO, AYALA_AIARA, BAKIO,
	BALMASEDA, BARAKALDO, BARRIKA, BASAURI, BEDIA, BERANGO, BERMEO, BERRIATUA, BERRIZ, BILBAO, BUSTURIA, CASTROURDIALES,
	DERIO, DIMA, DURANGO, EA, ELANTXOBE, ELORRIO, ERANDIO, EREÑO, ERMUA, ERRIGOITI, ETXEBARRI, ETXEBARRIA, FORUA, FRUIZ,
	GALDAKAO, GALDAMES, GAMIZFIKA, GARAI, GATIKA, GAUTEGIZ, GAZTELUELEXABEITIA_ARTEAGA, GERNIKALUMO, GETXO, GIZABURUAGA,
	GORDEXOLA, GORLIZ, GUEÑES, IBARRANGELU, IGORRE, ISPASTER, IURRETA, IZURTZA, KARRANTZAHARANA, KORTEZUBI, LANESTOSA,
	LARRABETZU, LAUDIO_LLODIO, LAUKIZ, LEIOA, LEKEITIO, LEMOA, LEMOIZ, LEZAMA, LOIU, MALLABIA, MAÑARIA, MARKINAXEMEIN,
	MARURI, MENDATA, MENDEXA, MEÑAKA, MORGA, MUNDAKA, MUNGIA, MUNITIBARARBATZEGI_GERRIKAITZ, MURUETA, MUSKIZ, MUXIKA,
	NABARNIZ, ONDARROA, ORDUÑA, OROZKO, ORTUELLA, OTXANDIO, PLENTZIA, PORTUGALETE, SANTURTZI, SESTAO, SONDIKA, SOPELA,
	SOPUERTA, SUKARRIETA, TRAPAGARAN, TURTZIOZ, UBIDE, UGAOMIRABALLES, URDULIZ, URDUÑA, USANSOLO, ZALDIBAR, ZALLA,
	ZAMUDIO, ZARATAMO, ZEANURI, ZEBERIO, ZIERBENA, ZIORTZA_BOLIBAR, ZORNOTZA
}
