package enums;

public enum Sector {
	UNSET, AGRICULTURA_GANADERIA, BIENESCONSUMO, COMERCIOELECTRONICO, COMERCIO_ESTABLECIMIENTOS, CONSTRUCCION,
	DEPORTE_OCIO, ENERGIA_MEDIOAMBIENTE, FINANZAS_SEGUROS_BIENESINMUEBLES, INTERNET, LOGISTICA_TRANSPORTE,
	MEDIOSCOMUNICACION_MARKETING, METALURGIA_ELECTRONICA, PRODUCTOSQUIMICOS_MATERIASPRIMAS, SALUD_INDUSTRIAFARMACEUTICA,
	SERVICIOS, SOCIEDAD, TECNOLOGIA_TELECOMUNICACIONES, TURISMO_HOSTELERIA, VIDA
}
